### ISSUE TITLE
Sendmail broken…

### ISSUE THREAD

**Issue by tterragcnoom** [banks/kohana-email#1]
I believe the sendmail portion of this module is broken. It appears as if the Swift_SendmailTransport does not support the setTimeout Function and is automatically set to 30 seconds. Anyway, it can be fixed by removing line 63 of classes/email.php

Thanks for the module!

**Comment by banks** [comment]
Thanks for this - I've not actually used the module since I ported it from KO2! I'll have a look at this though.

**Comment by banks** [comment]
Fixed by fffda8e
